trigger_topic: "/bdd/start"
topic_sets:
  icra-sim:
    - "/bdd/status"
    - "/bdd/events"
    - "/obs_policy/container_not_dropped"
    - "/ee_wrench"
    - "/ee_wrench_est"
    - "/sim/ground_truth/recognized_objects"
    - "/recognized_objects"
    - "/tf"
    - "/tf_static"
    - "/joint_states"
    - "/clock"
  icra-real:
    - "/bdd/status"
    - "/bdd/events"
    - "/obs_policy/container_not_dropped"
    - "/ee_wrench"
    - "/ee_wrench_est"
    - "/recognized_objects"
    - "/tf"
    - "/tf_static"
    - "/joint_states"
